//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassCoreAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlassCoreEntities : DbContext
    {
        public GlassCoreEntities()
            : base("name=GlassCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Asignatura> Asignatura { get; set; }
        public virtual DbSet<Asignatura_Cod> Asignatura_Cod { get; set; }
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Dias> Dias { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Estudiante_Soporte> Estudiante_Soporte { get; set; }
        public virtual DbSet<Horario_Estudiante_Reporte> Horario_Estudiante_Reporte { get; set; }
        public virtual DbSet<Horario_Profesor> Horario_Profesor { get; set; }
        public virtual DbSet<Pesum> Pesum { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Profesor_Soporte> Profesor_Soporte { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
