//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassCoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_Estudiante_Reporte
    {
        public int Id_Estudiante { get; set; }
        public int Id_Asignatura { get; set; }
        public int Seccion { get; set; }
        public int Id_Profesor { get; set; }
        public int Trimestre { get; set; }
        public Nullable<int> Medio_Termino { get; set; }
        public string Calificacion_Final { get; set; }
        public Nullable<int> Puntos { get; set; }
        public int Id_Dia { get; set; }
        public string Estado { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Dias Dias { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
