//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassCoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int Id { get; set; }
        public int Id_Estudiante { get; set; }
        public int Id_Seccion { get; set; }
        public Nullable<int> Calificacion_MD { get; set; }
        public string Calificacion_Final { get; set; }
        public int Id_Aula { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
