//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassCoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor_Soporte
    {
        public int Id_Administrador { get; set; }
        public int Id_Profesor { get; set; }
        public string Mensaje { get; set; }
        public string Estado { get; set; }
        public int Id_Nota { get; set; }
        public System.DateTime Fecha_Enviada { get; set; }
        public System.DateTime Fecha_Respondida { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
