//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassCoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        public int Id_Seccion { get; set; }
        public int Id_Asignatura { get; set; }
        public Nullable<int> Num_Seccion { get; set; }
        public Nullable<int> Id_Profesor { get; set; }
        public Nullable<int> Id_Ciclo { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }
        public int Id_Dia { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Ciclo Ciclo { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
