//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassCoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Id_Tarea { get; set; }
        public int Id_Estudiante { get; set; }
        public string Mensaje { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Cierre { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
